/// Written to the config path on first run when no config exists.
public enum DefaultConfig {
    public static let text = #"""
-- ============================================================================
--  hyprdarwin config - AUTOGENERATED on first run.
--  hyprdarwin never writes this file again: edit it freely, comments survive.
--  Saving reloads it automatically; on an error the previous config stays
--  active and the menu bar shows what went wrong (menu > Show Errors...).
--
--  The API is a subset of Hyprland 0.56's Lua config (hl.*). Options macOS
--  cannot honour (blur, animations, rounding...) are accepted and ignored.
--  See the README for the full list of supported calls.
-- ============================================================================

-- HYPR is the Hypr key: Caps Lock, remapped to F18 by hyprdarwin while it runs.
-- Swap in "CMD + ALT" (or anything else) if you prefer.
local mod = "HYPR"

local terminal = "open -na Ghostty || open -a Terminal"

-------------------
---- LOOK & FEEL ---
-------------------

hl.config({
    general = {
        layout   = "dwindle", -- "dwindle" or "master"; per workspace via hl.workspace_rule
        gaps_in  = 5,         -- between windows (each side), or "top right bottom left"
        gaps_out = 12,        -- around the screen edge
    },

    dwindle = {
        preserve_split = true, -- keep each split's direction when windows come and go
        -- force_split = 0,    -- 0: follow the cursor, 1: new window left/top, 2: right/bottom
        -- default_split_ratio = 1.0,
    },

    master = {
        mfact       = 0.55,
        new_status  = "slave", -- "master", "slave" or "inherit"
        orientation = "left",  -- "left", "right", "top" or "bottom"
    },

    input = {
        follow_mouse = 1, -- 1: focus follows the cursor, 0: focus on click
    },

    misc = {
        -- false: a new window opens on its workspace without taking focus or
        -- switching workspaces (you stay where you are); true: focus follows it
        focus_on_open = false,
        -- disable_autoreload = false,
    },

    -- cursor = { no_warps = false }, -- keyboard focus moves the cursor along
})

-- macOS-only settings live under `hd`, which is nil on Hyprland, so a shared
-- dotfile can keep them behind `if hd then`.
if hd then
    hd.config({
        hypr_key    = "caps_lock",    -- "caps_lock", "f18" (already remapped elsewhere) or "none"
        hide_corner = "bottom-right", -- where hidden workspaces' windows are parked
        -- unmanaged_apps = { "com.mitchellh.ghostty" }, -- bundle ids hyprdarwin never moves
    })
end

------------------
---- WORKSPACES ---
------------------

-- Workspaces are created on demand (1-10 have default binds; any number works).
-- hl.workspace_rule({ workspace = "1", monitor = "DELL U3423WE", default = true })
-- hl.workspace_rule({ workspace = "5", layout = "master" })
-- hl.workspace_rule({ workspace = "9", gaps_in = 0, gaps_out = 0 })

-------------------
---- KEYBINDINGS ---
-------------------

hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd(terminal),                 { description = "Terminal" })
hl.bind(mod .. " + Q",      hl.dsp.window.close(),                     { description = "Close window" })
hl.bind(mod .. " + V",      hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating" })
-- "maximized" fills the tiling area (inside gaps_out); "fullscreen" the whole screen below the menu bar.
-- Either way the workspace's other windows step aside until it ends.
hl.bind(mod .. " + F",         hl.dsp.window.fullscreen({ mode = "maximized" }), { description = "Toggle maximized" })
hl.bind(mod .. " + SHIFT + F", hl.dsp.window.fullscreen(),                       { description = "Toggle fullscreen" })
hl.bind(mod .. " + C",      hl.dsp.window.center(),                    { description = "Center floating window" })
hl.bind(mod .. " + SPACE",  hl.dsp.layout("togglesplit"),              { description = "Toggle split (dwindle)" })
hl.bind(mod .. " + SHIFT + RETURN", hl.dsp.layout("swapwithmaster"),   { description = "Swap with master (master)" })
hl.bind(mod .. " + SHIFT + R", hl.dsp.reload_config(),                 { description = "Reload config" })
if hd then
    -- this workspace switches between dwindle and master (hyprdarwin-only)
    hl.bind(mod .. " + SHIFT + SPACE", hd.dsp.cycle_layout(), { description = "Cycle layout (dwindle / master)" })
end

-- Vim-style focus (h/j/k/l), swap (SHIFT) and move (CTRL); the arrow keys work too.
-- Move swaps with the neighbour, or hops to the next monitor at the edge.
local directions = {
    h = "left", j = "down", k = "up", l = "right",
    left = "left", down = "down", up = "up", right = "right",
}
for key, dir in pairs(directions) do
    hl.bind(mod .. " + " .. key,         hl.dsp.focus({ direction = dir }))
    hl.bind(mod .. " + SHIFT + " .. key, hl.dsp.window.swap({ direction = dir }))
    hl.bind(mod .. " + CTRL + " .. key,  hl.dsp.window.move({ direction = dir }))
end

-- Workspaces 1-10 (key 0 is workspace 10). SHIFT moves the window and follows it;
-- CTRL + SHIFT moves it silently.
for i = 1, 10 do
    local key = tostring(i % 10)
    hl.bind(mod .. " + " .. key,                hl.dsp.focus({ workspace = i }))
    hl.bind(mod .. " + SHIFT + " .. key,        hl.dsp.window.move({ workspace = i }))
    hl.bind(mod .. " + CTRL + SHIFT + " .. key, hl.dsp.window.move({ workspace = i, follow = false }))
end
hl.bind(mod .. " + TAB",          hl.dsp.focus({ workspace = "previous" }), { description = "Previous workspace" })
hl.bind(mod .. " + bracketright", hl.dsp.focus({ workspace = "e+1" }),      { description = "Next workspace" })
hl.bind(mod .. " + bracketleft",  hl.dsp.focus({ workspace = "e-1" }),      { description = "Previous existing workspace" })

-- Scratchpad (special workspace).
hl.bind(mod .. " + S",         hl.dsp.workspace.toggle_special("scratch"),             { description = "Toggle scratchpad" })
hl.bind(mod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:scratch" }), { description = "Move to scratchpad" })

-- Resize mode: HYPR + R, then arrows; Escape or Return leaves.
hl.bind(mod .. " + R", hl.dsp.submap("resize"), { description = "Resize mode" })
hl.define_submap("resize", function()
    hl.bind("right",  hl.dsp.window.resize({ x =  40, y =   0, relative = true }), { repeating = true })
    hl.bind("left",   hl.dsp.window.resize({ x = -40, y =   0, relative = true }), { repeating = true })
    hl.bind("down",   hl.dsp.window.resize({ x =   0, y =  40, relative = true }), { repeating = true })
    hl.bind("up",     hl.dsp.window.resize({ x =   0, y = -40, relative = true }), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("return", hl.dsp.submap("reset"))
end)

--------------------
---- WINDOW RULES ---
--------------------

-- match: class = bundle id, title = window title, plus initial_class,
-- initial_title, app_name, role and subrole (AX). Values are regexes,
-- unanchored; prefix "negative:" to invert. Later rules win per effect.
hl.window_rule({ name = "float-dialogs",  match = { subrole = "^AX(Dialog|SystemDialog|FloatingWindow)$" }, float = true })
hl.window_rule({ name = "float-settings", match = { class = "^com\\.apple\\.systempreferences$" }, float = true, center = true })
hl.window_rule({ name = "float-facetime", match = { class = "^com\\.apple\\.FaceTime$" }, float = true })
hl.window_rule({ name = "float-finder-ops", match = { class = "^com\\.apple\\.finder$", title = "^(Copy|Move|Connect to Server)" }, float = true })
hl.window_rule({ name = "float-pip", match = { title = "^Picture[- ]in[- ]Picture$" }, float = true, size = "480 270", move = "monitor_w-500 20" })

-- Examples:
-- hl.window_rule({ match = { class = "^com\\.tinyspeck\\.slackmacgap$" }, workspace = "3 silent" })
-- hl.window_rule({ match = { class = "^com\\.apple\\.calculator$" }, float = true, center = true })

-----------------
---- AUTOSTART ---
-----------------

-- Runs once when hyprdarwin starts (not on reload).
-- hl.on("hyprland.start", function()
--     hl.exec_cmd("open -a Ghostty")
-- end)
"""#
}
